apiVersion: non-margo.org
kind: ApplicationDeployment
metadata:
  name: my-app-deployment
spec:
  appPackageRef:
    id: 69391e61-22be-4603-890b-bcbcc32be6cb
  deviceRef:
    id: device-101
  deploymentProfile:
    type: helm.v3
    components:
      - name: digitron-orchestrator
        properties:
          repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
          revision: 1.0.9
          wait: true
  parameters:
    pollFrequency:
      value: "60"
      targets:
        - pointer: settings.pollFrequency
          components: [digitron-orchestrator]